- en: P29：Talks - Dawn Wages_ Supercharge your Python Development Environment with
    VS Code - VikingDen7 - BV1114y1o7c5
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: P29：演讲 - Dawn Wages_ 使用 VS Code 超级充电你的 Python 开发环境 - VikingDen7 - BV1114y1o7c5
- en: '[ Inaudible ]。'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_1.png)'
  id: totrans-2
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_1.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见
    ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_3.png)'
  id: totrans-4
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_3.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]， [ Inaudible ]。'
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见
    ]。'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]。'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_5.png)'
  id: totrans-7
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_5.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_7.png)'
  id: totrans-9
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_7.png)'
- en: '[ Inaudible ]。'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_9.png)'
  id: totrans-11
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_9.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]。'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_11.png)'
  id: totrans-13
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_11.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]。'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]， [ 无法听见
    ]， [ 无法听见 ]， [ 无法听见 ]。 [ 无法听见 ]， [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_13.png)'
  id: totrans-15
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_13.png)'
- en: '[ Inaudible ]， [ Inaudible ]。'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_15.png)'
  id: totrans-17
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_15.png)'
- en: '[ Inaudible ]。'
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_17.png)'
  id: totrans-19
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_17.png)'
- en: '[ Inaudible ]。'
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_19.png)'
  id: totrans-21
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_19.png)'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_20.png)'
  id: totrans-22
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_20.png)'
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]， [ 无法听见 ]。'
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_22.png)'
  id: totrans-24
  prefs: []
  type: TYPE_IMG
  zh: '![](img/3e973d17e09a758ba1ad35e8173d8b88_22.png)'
- en: '[ Inaudible ]， [ Inaudible ]。'
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 无法听见 ]， [ 无法听见 ]。'
