- en: P29：Talks - Dawn Wages_ Supercharge your Python Development Environment with
    VS Code - VikingDen7 - BV1114y1o7c5
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: '[ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_1.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_3.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_5.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_7.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_9.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_11.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible
    ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]， [ Inaudible ]， [ Inaudible ]，
    [ Inaudible ]， [ Inaudible ]。 [ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_13.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_15.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_17.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_19.png)'
  prefs: []
  type: TYPE_IMG
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_20.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3e973d17e09a758ba1ad35e8173d8b88_22.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Inaudible ]， [ Inaudible ]。'
  prefs: []
  type: TYPE_NORMAL
