- en: P42：Talks - Joongi Kim_ Improving debuggability of complex asyncio applications
    - VikingDen7 - BV1114y1o7c5
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: '[ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_1.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Pause ]， [ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_3.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [
    Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_5.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_7.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Pause ]， [ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_9.png)'
  prefs: []
  type: TYPE_IMG
- en: '[ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [
    Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause
    ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '[ Pause ]。'
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_11.png)'
  prefs: []
  type: TYPE_IMG
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_12.png)'
  prefs: []
  type: TYPE_IMG
