- en: P42：Talks - Joongi Kim_ Improving debuggability of complex asyncio applications
    - VikingDen7 - BV1114y1o7c5
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: P42：演讲 - 金俊基_ 改进复杂 asyncio 应用的可调试性 - VikingDen7 - BV1114y1o7c5
- en: '[ Pause ]。'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_1.png)'
  id: totrans-2
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_1.png)'
- en: '[ Pause ]， [ Pause ]。'
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]， [ 暂停 ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_3.png)'
  id: totrans-4
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_3.png)'
- en: '[ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [
    Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]。'
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。 [ 暂停
    ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。 [ 暂停 ]， [ 暂停
    ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_5.png)'
  id: totrans-6
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_5.png)'
- en: '[ Pause ]。'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_7.png)'
  id: totrans-8
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_7.png)'
- en: '[ Pause ]， [ Pause ]。'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]， [ 暂停 ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_9.png)'
  id: totrans-10
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_9.png)'
- en: '[ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [
    Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]， [ Pause ]， [ Pause
    ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。 [ Pause ]， [ Pause ]，
    [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]， [ Pause ]。'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。 [ 暂停
    ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。 [ 暂停 ]， [ 暂停
    ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。 [ 暂停 ]， [ 暂停 ]， [ 暂停
    ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]， [ 暂停 ]。'
- en: '[ Pause ]。'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: '[ 暂停 ]。'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_11.png)'
  id: totrans-13
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_11.png)'
- en: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_12.png)'
  id: totrans-14
  prefs: []
  type: TYPE_IMG
  zh: '![](img/e51a549fc40cd7270ffb9fb6a33681ca_12.png)'
