- en: P65：Talks - Ron Nathaniel_ How To Monitor and Troubleshoot Applications using
    OpenTe - VikingDen7 - BV1114y1o7c5
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: P65：谈话 - **罗恩·纳撒尼尔**_ 如何使用 OpenTe 监控和故障排除应用程序 - VikingDen7 - BV1114y1o7c5
- en: '[inaudible]。'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不见]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_1.png)'
  id: totrans-2
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_1.png)'
- en: '[inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]。'
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不见]， [听不见]， [听不见]， [听不见]， [听不见]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_3.png)'
  id: totrans-4
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_3.png)'
- en: '[inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]。'
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_5.png)'
  id: totrans-6
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_5.png)'
- en: '[inaudible]， [inaudible]。'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]， [听不清]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_7.png)'
  id: totrans-8
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_7.png)'
- en: '[inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]， [inaudible]， [inaudible]。'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。'
- en: '[inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]， [inaudible]， [inaudible]。'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。'
- en: '[inaudible]。'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不见]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_9.png)'
  id: totrans-12
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_9.png)'
- en: '[inaudible]， [inaudible]。'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不见]， [听不见]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_11.png)'
  id: totrans-14
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_11.png)'
- en: '[inaudible]。'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_13.png)'
  id: totrans-16
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_13.png)'
- en: '[inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]。 [inaudible]， [inaudible]， [inaudible]， [inaudible]， [inaudible]，
    [inaudible]， [inaudible]。 [inaudible]， [inaudible]， [inaudible]。'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: '[听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]， [听不清]，
    [听不清]， [听不清]， [听不清]。 [听不清]， [听不清]， [听不清]。'
- en: '![](img/afeb7529b78d74d49398d0f57fb6371e_15.png)'
  id: totrans-18
  prefs: []
  type: TYPE_IMG
  zh: '![](img/afeb7529b78d74d49398d0f57fb6371e_15.png)'
